import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import productGeneral from '@/mocks/product'

type IProps = {
  id: Number;
  slug: String;
  header: {
    title: String;
  }
  usAmount: Number;
  discount: String;
  variations: {
    size: String;
    color: String;
    style: String;
    usAmount: Number;
  }[];
  description: String;
  images: {
    isCover: Boolean;

    color: String;
    style: String;
    usAmount: Number;
  }[];
  videoUrl: String;
  title: String;
  category: String;
}
function ProductDetail({
  data
}: {
  data: IProps
}) {
  return (
    <div>
      <Head>
        <title>{data.header.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-3xl font-bold underline">
          hello word productdetail
          {data.header.title}
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const data: IProps = productGeneral.buildProductDetail({})

  // // Pass data to the page via props
  return { props: { data } }
}

export default ProductDetail
